# Generated by Django 4.1.7 on 2023-09-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_remove_session_client_remove_session_instructor_and_more'),
        ('instructor', '0002_remove_rating_client_remove_rating_instructor_and_more'),
        ('client', '0002_alter_information_online_lesson_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='TextClientRegister',
        ),
        migrations.DeleteModel(
            name='TextClientUpdate',
        ),
    ]
